[package]
name = "sqlite-sample"
version = "0.0.1-alpha.1"
license = "MIT OR Apache"
homepage = "https://alexgarcia.xyz/sqlite-sample"
repo = "https://github.com/asg017/sqlite-sample"
description = "A sample SQLite extension to test sqlite-dist."
authors = ["Alex Garcia"]

[targets]
github_releases = {}
sqlpkg = {}
spm = {}

pip = {}
datasette = {}
sqlite_utils = {}

npm = {}

gem = { module_name="SqliteSample" }
