[package]
name = "sqlite-sample"
license = "MIT OR Apache"
homepage = "https://alexgarcia.xyz/sqlite-sample"
repo = "https://github.com/asg017/sqlite-sample"
description = "A sample SQLite extension to test sqlite-dist."
authors = ["Alex Garcia"]

[targets]
github_releases = {}
sqlpkg = {}
spm = {}
amalgamation = {include=["sqlite-sample.c", "sqlite-sample.h"]}

pip = { extra_init_py = "extra_init.py" }
datasette = {}
sqlite_utils = {}

npm = {}

gem = { module_name="SqliteSample" }
